export const PERMISSION_BEGIN = 'PERMISSION_BEGIN'
export const PERMISSION_ERROR = 'PERMISSION_ERROR'
export const PERMISSION_ASKED = 'PERMISSION_ASKED'
export const PERMISSION_GRANTED = 'PERMISSION_GRANTED'
