export const APPLICATION_BEGIN = 'APPLICATION_BEGIN'
export const CONFIGURATION_LOADED = 'CONFIGURATION_LOADED'
export const APPLICATION_ERROR = 'APPLICATION_ERROR'
export const APPLICATION_LOCATION = 'APPLICATION_LOCATION'
